# Generated by Django 5.2.14 on 2026-05-19 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.CharField(max_length=250)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('genero', models.CharField(choices=[('R', 'Rock'), ('P', 'Pop')], default='R', max_length=1)),
                ('fecha_creacion', models.DateField()),
                ('eventos', models.ManyToManyField(to='catalogoMusicos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('pago', models.FloatField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anuncios', to='catalogoMusicos.banda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anuncios', to='catalogoMusicos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion_error', models.TextField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reportes', to='catalogoMusicos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogoMusicos.usuario')),
                ('instrumento', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=250)),
                ('fecha_inicio_estudio', models.DateField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musico_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('catalogoMusicos.usuario',),
        ),
        migrations.AddField(
            model_name='banda',
            name='musicos',
            field=models.ManyToManyField(to='catalogoMusicos.musico'),
        ),
    ]
