# Generated by Django 5.2.12 on 2026-05-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoMusicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='generos_tags',
        ),
    ]
