# Generated by Django 5.2.14 on 2026-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogoMusicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musico",
            name="fecha_inicio_estudio",
            field=models.DateField(),
        ),
    ]
