# Generated by Django 5.2.14 on 2026-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoMusicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
