# Generated by Django 5.2.14 on 2026-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoMusicos', '0002_evento_latitud_evento_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
