# Configuración

server {
    listen 8000;
    location /static/ {
        alias /staticfiles_catalogomusicos/;
    }
    location / {
        proxy_pass http://web-catalogomusicos:8000;
        proxy_set_header Host $host;
    }
}
